#include <string>
using namespace std;

/*
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"
Output:
e
Explanation:
'e' is the letter that was added.

解题思路：
a^a为0，0^a为a
因此把s和t所有字符依次全部^，最后的结果为多的那个字符的值
*/

class Solution {
public:
	char findTheDifference(string s, string t) {
		char res = 0;
		for (char i : t) res ^= i;
		for (char i : s) res ^= i;
		return res;
	}
};